### ISSUE TITLE
HTML has no content?

### ISSUE THREAD

**Issue by davidheis** [learn-co-curriculum/listening-to-dom-nodes#7] opened 2016-12-22 10:09 UTC
It says 'Let's start by adding a listener for click events to the main#main element in index.html'

But there is no content in the HTML. Are we supposed to create the content ourselves beforehand?

**Comment by aturkewi** [comment] 2017-01-13 19:14
Hey @davidheis I'm not sure I see what you're talking about here. I'm looking at the lab and it looks like the HTML does have content: https://github.com/learn-co-curriculum/listening-to-dom-nodes/blob/master/index.html
Are you seeing something different?

**Comment by JessRudder** [comment] 2017-05-02 17:51
Going to close this issue due to lack of reproducibility.  Feel free to re-open it if you have more detail to provide.

**Closed as completed by JessRudder** 2017-05-02 17:51 UTC
Labels: Test
